### ISSUE TITLE
HMR is not working

### ISSUE THREAD

**Issue by krzysztofpniak** [salsita/redux-elm-skeleton#4]
As in title, I know that some time ago it was a branch called HMR, but it wasn't merged to master. Anyways, after I found that commit and applied it manually I found a really strang problem. Style attribute seems not working I'm not sure if problem is caused by webpack, react or elm library.

Steps to reproduce:
1. create html like this in some place in JSX:
   <div>Hello</div>
2. run HMR
3. add style attribute with unknown variable:
   <div style={{color: orange}}>Hello</div>
4. It will raise an error in console which is correct
5. Now try to fix this problem:
   <div style={{color: 'orange'}}>Hello</div>
6. Now there is no error, but color is not applied.
7. After full page refresh color works.

**Comment by tomkis** [comment]
I believe the HMR branch was outdated because of 3.x `redux-elm` transition. Here's a new branch https://github.com/salsita/redux-elm-skeleton/tree/hmr

We want to keep this in separate branch because we are using this repo throughout the `redux-elm` documentation so it needs to be as lightweight as possible. The branch is just a recipe how to utilize HMR.
